// Generated by https://quicktype.io

export interface CreatedListPersonalResponse {
    success:        boolean;
    status_code:    number;
    status_message: string;
    list_id:        number;
}
