// Generated by https://quicktype.io

export interface ListPesonalDetailsResponse {
  created_by: string;
  description: string;
  favorite_count: number;
  id: number;
  iso_639_1: string;
  item_count: number;
  items: Item[];
  name: string;
  page: number;
  poster_path: null;
  total_pages: number;
  total_results: number;
}
export enum ISO639_1 {
  En = 'en',
}

export interface Item {
  adult: boolean;
  backdrop_path: string;
  genre_ids: number[];
  id: number;
  media_type: MediaType;
  original_language: ISO639_1;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  release_date: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

export enum MediaType {
  Movie = 'movie',
}
