// Generated by https://quicktype.io

export interface MovieListPersonalResponse {
    page:          number;
    results:       ListMovie[];
    total_pages:   number;
    total_results: number;
}
export interface ListMovie {
    description: string;
    favorite_count: number;
    id: number;
    item_count: number;
    iso_639_1: ISO639_1;
    list_type: ListType;
    name: string;
    poster_path: null | string;
}

export enum ISO639_1 {
    En = "en",
}

export enum ListType {
    Movie = "movie",
}